name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Draft Release"
        uses: release-drafter/release-drafter@v5.20.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
